import type { Metadata } from "next";
import { Bricolage_Grotesque, Manrope } from "next/font/google";
import "./globals.css";

const brico = Bricolage_Grotesque({
  variable: "--font-brico",
  subsets: ["latin"],
});

const man = Manrope({
  variable: "--font-man",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brico.variable} ${man.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
